import {
  IsHash,
  IsEnum,
  IsEmail,
  IsString,
  MaxLength,
  MinLength,
  IsNotEmpty,
  IsOptional,
  IsPhoneNumber,
  IsNumberString,
} from 'class-validator';
import { Transform } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';
import {
  trimTransformer,
  toLowerCaseTransformer,
} from '@app/common/src/helpers/local-class-validator';

export class UpdateFCMTokenDTO {
  @ApiProperty({
    example: '1733689739675',
    description: 'FCM token for push notifications generated by mobile device.',
  })
  @IsString()
  @IsNotEmpty()
  fcmToken: string;
}

export class UpdateProfileImageDTO {
  @ApiProperty({
    example: 'https://example.com/image.jpg',
    description: 'URL of the image to be uploaded.',
  })
  @IsString()
  @IsNotEmpty()
  imageUrl: string;
}

export class UpdateAccountPasswordDTO {
  @ApiProperty({
    example: 'Password123',
    description: 'Current account password.',
  })
  @IsString()
  @IsNotEmpty()
  currentPassword: string;

  @ApiProperty({
    example: 'Password@123',
    description: 'New account password.',
  })
  @IsString()
  @IsNotEmpty()
  newPassword: string;
}

export class DeleteAccountDTO {
  @ApiProperty({
    example: 'Password123',
    description: 'Current account password.',
  })
  @IsString()
  @IsNotEmpty()
  password: string;
}

export class UpdateAccountNameDTO {
  @ApiProperty({
    example: 'John',
    description: 'New account first name.',
  })
  @IsString()
  @IsNotEmpty()
  firstName: string;

  @ApiProperty({
    example: 'Doe',
    description: 'New account last name.',
  })
  @IsString()
  @IsNotEmpty()
  lastName: string;
}

export class UpdateAccountEmailDTO {
  @ApiProperty({
    example: 'kunle@gmail.com',
    description: 'New account email.',
  })
  @IsEmail()
  @IsNotEmpty()
  @Transform(({ value }) => trimTransformer(toLowerCaseTransformer(value)))
  newEmail: string;
}

export class VerifyNewAccountEmailDTO {
  @ApiProperty({
    example: '3950',
    description: 'Activation token (OTP)',
  })
  @IsString()
  @IsNotEmpty()
  otp: string;
}

export class UpdateAccountPhoneDTO {
  @ApiProperty({
    example: '+2349093920293',
    description: 'New account phone.',
  })
  @IsNotEmpty()
  @IsString()
  @Transform(({ value }) => trimTransformer(value))
  newPhone: string;

  @ApiProperty({
    example: 'Password123',
    description: 'Account password.',
  })
  @IsString()
  @IsNotEmpty()
  password: string;
}

export class UpdateAccountLocationDTO {
  @ApiProperty({
    example: 'Lagos',
    description: 'User state.',
  })
  @IsString()
  @IsNotEmpty()
  state: string;

  @ApiProperty({
    example: 'Ikeja',
    description: 'User city.',
  })
  @IsString()
  @IsNotEmpty()
  city: string;
}
