import * as fs from 'fs';
import * as path from 'path';
import * as Papa from 'papaparse';
import { Injectable, Logger, OnModuleInit } from '@nestjs/common';

@Injectable()
export class AddressHelperService implements OnModuleInit {
  private zipData: any[];
  private readonly logger = new Logger(AddressHelperService.name);

  onModuleInit() {
    this.loadZipData();
  }

  constructor() {}

  private loadZipData() {
    const filePath = path.join(
      process.cwd(),
      'libs',
      'helper-service',
      'src',
      'data',
      'uszips.csv',
    );

    if (!fs.existsSync(filePath)) {
      this.logger.error(`CSV file not found at: ${filePath}`);
      throw new Error('CSV file not found');
    }

    const fileContent = fs.readFileSync(filePath, 'utf-8');

    const parsedData = Papa.parse(fileContent, {
      header: true,
      skipEmptyLines: true,
    });

    // this.logger.error(`CSV file found at: ${filePath}`);

    this.zipData = parsedData.data;
  }

  formatZipCode(value: string) {
    if (value.length === 3) {
      return '00'.concat(value);
    }
    if (value.length === 4) {
      return '0'.concat(value);
    }

    return value;
  }

  async fetchZipCodeInformation(zipCode: number): Promise<{
    city: string;
    state: string;
    county: string;
    zipCode: string;
  } | null> {
    try {
      this.logger.log(`[FETCH-ZIP-CODE-DATA-PROCESSING]`);

      const result = await this.zipData.find((row) => row.zip == zipCode);

      this.logger.log(`[FETCH-ZIP-CODE-DATA-SUCCESS]`);

      if (result) {
        return {
          city: result.city,
          state: result.state_name,
          county: result.county_name,
          zipCode: this.formatZipCode(result.zip),
        };
      }

      return null;
    } catch (error) {
      this.logger.error(`[FETCH-ZIP-CODE-DATA-ERROR]`);
    }
  }

  async getUniqueStates(): Promise<
    Array<{ stateId: string; stateName: string; lgas: string[] }>
  > {
    try {
      const nigerianStates = [
        {
          stateId: 'AB',
          stateName: 'Abia',
          lgas: [
            'Aba',
            'Umuahia',
            'Aba North',
            'Aba South',
            'Isiala Ngwa',
            'Arochukwu',
            'Bende',
            'Ikwuano',
            'Isiala Ngwa North',
            'Isiala Ngwa South',
            'Isuikwuato',
            'Obi Ngwa',
            'Ohafia',
            'Osisioma',
            'Ugwunagbo',
            'Ukwa East',
            'Ukwa West',
            'Umuahia North',
            'Umuahia South',
            'Umu Nneochi',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'AD',
          stateName: 'Adamawa',
          lgas: [
            'Yola',
            'Demsa',
            'Fufure',
            'Ganye',
            'Girei',
            'Gombi',
            'Guyuk',
            'Hong',
            'Jada',
            'Lamurde',
            'Madagali',
            'Maiha',
            'Mayo Belwa',
            'Michika',
            'Mubi North',
            'Mubi South',
            'Numan',
            'Shelleng',
            'Song',
            'Toungo',
            'Yola North',
            'Yola South',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'AK',
          stateName: 'Akwa Ibom',
          lgas: [
            'Abak',
            'Eastern Obolo',
            'Eket',
            'Esit Eket',
            'Essien Udim',
            'Etim Ekpo',
            'Etinan',
            'Ibeno',
            'Ibesikpo Asutan',
            'Ibiono-Ibom',
            'Ika',
            'Ikono',
            'Ikot Abasi',
            'Ikot Ekpene',
            'Ini',
            'Itu',
            'Mbo',
            'Mkpat-Enin',
            'Nsit-Atai',
            'Nsit-Ibom',
            'Nsit-Ubium',
            'Obot Akara',
            'Okobo',
            'Onna',
            'Oron',
            'Oruk Anam',
            'Udung-Uko',
            'Ukanafun',
            'Uruan',
            'Urue-Offong/Oruko',
            'Uyo',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'AN',
          stateName: 'Anambra',
          lgas: [
            'Nnewi',
            'Awka',
            'Onitsha',
            'Aguata',
            'Anambra East',
            'Anambra West',
            'Anaocha',
            'Awka North',
            'Awka South',
            'Ayamelum',
            'Dunukofia',
            'Ekwusigo',
            'Idemili North',
            'Idemili South',
            'Ihiala',
            'Njikoka',
            'Nnewi North',
            'Nnewi South',
            'Ogbaru',
            'Onitsha North',
            'Onitsha South',
            'Orumba North',
            'Orumba South',
            'Oyi',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'BA',
          stateName: 'Bauchi',
          lgas: [
            'Alkaleri',
            'Bauchi',
            'Bogoro',
            'Damban',
            'Darazo',
            'Dass',
            'Gamawa',
            'Ganjuwa',
            'Giade',
            'Itas/Gadau',
            "Jama'are",
            'Katagum',
            'Kirfi',
            'Misau',
            'Ningi',
            'Shira',
            'Tafawa Balewa',
            'Toro',
            'Warji',
            'Zaki',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'BY',
          stateName: 'Bayelsa',
          lgas: [
            'Brass',
            'Ekeremor',
            'Kolokuma/Opokuma',
            'Nembe',
            'Ogbia',
            'Sagbama',
            'Southern Ijaw',
            'Yenagoa',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'BE',
          stateName: 'Benue',
          lgas: [
            'Ado',
            'Agatu',
            'Apa',
            'Buruku',
            'Gboko',
            'Guma',
            'Gwer East',
            'Gwer West',
            'Katsina-Ala',
            'Konshisha',
            'Kwande',
            'Logo',
            'Makurdi',
            'Obi',
            'Ogbadibo',
            'Ohimini',
            'Oju',
            'Okpokwu',
            'Otukpo',
            'Tarka',
            'Ukum',
            'Ushongo',
            'Vandeikya',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'BO',
          stateName: 'Borno',
          lgas: [
            'Abadam',
            'Askira/Uba',
            'Bama',
            'Bayo',
            'Biu',
            'Chibok',
            'Damboa',
            'Dikwa',
            'Gubio',
            'Guzamala',
            'Gwoza',
            'Hawul',
            'Jere',
            'Kaga',
            'Kala/Balge',
            'Konduga',
            'Kukawa',
            'Kwaya Kusar',
            'Mafa',
            'Magumeri',
            'Maiduguri',
            'Marte',
            'Mobbar',
            'Monguno',
            'Ngala',
            'Nganzai',
            'Shani',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'CR',
          stateName: 'Cross River',
          lgas: [
            'Abi',
            'Akamkpa',
            'Akpabuyo',
            'Bakassi',
            'Bekwarra',
            'Biase',
            'Calabar South',
            'Boki',
            'Calabar Municipal',
            'Calabar South',
            'Etung',
            'Ikom',
            'Obanliku',
            'Obubra',
            'Obudu',
            'Odukpani',
            'Ogoja',
            'Yakuur',
            'Yala',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'DE',
          stateName: 'Delta',
          lgas: [
            'Aniocha North',
            'Aniocha South',
            'Bomadi',
            'Ugheli',
            'Isoko',
            'Agbor',
            'Burutu',
            'Ethiope East',
            'Ethiope West',
            'Ika North East',
            'Ika South',
            'Isoko North',
            'Isoko South',
            'Ndokwa East',
            'Ndokwa West',
            'Okpe',
            'Oshimili North',
            'Oshimili South',
            'Patani',
            'Sapele',
            'Udu',
            'Ughelli North',
            'Ughelli South',
            'Ukwuani',
            'Uvwie',
            'Warri North',
            'Warri South',
            'Warri South West',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'EB',
          stateName: 'Ebonyi',
          lgas: [
            'Abakaliki',
            'Afikpo North',
            'Afikpo South',
            'Ebonyi',
            'Ezza North',
            'Ezza South',
            'Ikwo',
            'Ishielu',
            'Ivo',
            'Izzi',
            'Ohaozara',
            'Ohaukwu',
            'Onicha',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'ED',
          stateName: 'Edo',
          lgas: [
            'Akoko-Edo',
            'Egor',
            'Esan Central',
            'Esan North-East',
            'Esan South-East',
            'Esan West',
            'Etsako Central',
            'Etsako East',
            'Etsako West',
            'Igueben',
            'Benin City',
            'Benin',
            'Ikpoba Okha',
            'Oredo',
            'Orhionmwon',
            'Ovia North-East',
            'Ovia South-West',
            'Owan East',
            'Owan West',
            'Uhunmwonde',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'EK',
          stateName: 'Ekiti',
          lgas: [
            'Ado Ekiti',
            'Efon',
            'Ekiti East',
            'Ekiti South-West',
            'Ekiti West',
            'Emure',
            'Gbonyin',
            'Ido Osi',
            'Ijero',
            'Ikere',
            'Ikole',
            'Ilejemeje',
            'Irepodun/Ifelodun',
            'Ise/Orun',
            'Moba',
            'Oye',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'EN',
          stateName: 'Enugu',
          lgas: [
            'Aninri',
            'Awgu',
            'Enugu',
            'Enugu East',
            'Enugu North',
            'Enugu South',
            'Ezeagu',
            'Igbo Etiti',
            'Igbo Eze North',
            'Igbo Eze South',
            'Isi Uzo',
            'Nkanu East',
            'Nkanu West',
            'Nsukka',
            'Oji River',
            'Udenu',
            'Udi',
            'Uzo Uwani',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'ABJ',
          stateName: 'Abuja',
          lgas: [
            'Abaji',
            'Bwari',
            'Kuje',
            'Kwali',
            'Jiwa',
            'Garki 2',
            'Dei-Dei',
            'Gwagwalada',
            'Central Area',
            'Dutse-Alhaji',
            'Municipal Area',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'GO',
          stateName: 'Gombe',
          lgas: [
            'Akko',
            'Balanga',
            'Billiri',
            'Dukku',
            'Funakaye',
            'Gombe',
            'Kaltungo',
            'Kwami',
            'Nafada',
            'Shongom',
            'Yamaltu/Deba',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'IM',
          stateName: 'Imo',
          lgas: [
            'Aboh Mbaise',
            'Ahiazu Mbaise',
            'Ehime Mbano',
            'Ezinihitte',
            'Ideato North',
            'Owerri',
            'Ideato South',
            'Ihitte/Uboma',
            'Ikeduru',
            'Isiala Mbano',
            'Isu',
            'Mbaitoli',
            'Ngor Okpala',
            'Njaba',
            'Nkwerre',
            'Nwangele',
            'Obowo',
            'Oguta',
            'Ohaji/Egbema',
            'Okigwe',
            'Orlu',
            'Orsu',
            'Oru East',
            'Oru West',
            'Owerri Municipal',
            'Owerri North',
            'Owerri West',
            'Unuimo',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'JI',
          stateName: 'Jigawa',
          lgas: [
            'Auyo',
            'Babura',
            'Biriniwa',
            'Birnin Kudu',
            'Buji',
            'Dutse',
            'Gagarawa',
            'Garki',
            'Gumel',
            'Guri',
            'Gwaram',
            'Gwiwa',
            'Hadejia',
            'Jahun',
            'Kafin Hausa',
            'Kazaure',
            'Kiri Kasama',
            'Kiyawa',
            'Kaugama',
            'Maigatari',
            'Malam Madori',
            'Miga',
            'Ringim',
            'Roni',
            'Sule Tankarkar',
            'Taura',
            'Yankwashi',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KD',
          stateName: 'Kaduna',
          lgas: [
            'Birnin Gwari',
            'Chikun',
            'Giwa',
            'Igabi',
            'Ikara',
            'Jaba',
            "Jema'a",
            'Kachia',
            'Kaduna North',
            'Kaduna South',
            'Kagarko',
            'Kajuru',
            'Kaura',
            'Kauru',
            'Kubau',
            'Kudan',
            'Lere',
            'Makarfi',
            'Sabon Gari',
            'Sanga',
            'Soba',
            'Zangon Kataf',
            'Zaria',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KN',
          stateName: 'Kano',
          lgas: [
            'Ajingi',
            'Albasu',
            'Bagwai',
            'Bebeji',
            'Bichi',
            'Sabon gari',
            'Bunkure',
            'Dala',
            'Dambatta',
            'Dawakin Kudu',
            'Dawakin Tofa',
            'Doguwa',
            'Fagge',
            'Gabasawa',
            'Garko',
            'Garun Mallam',
            'Gaya',
            'Gezawa',
            'Gwale',
            'Gwarzo',
            'Kabo',
            'Kano Municipal',
            'Karaye',
            'Kibiya',
            'Kiru',
            'Kumbotso',
            'Kunchi',
            'Kura',
            'Madobi',
            'Makoda',
            'Minjibir',
            'Nasarawa',
            'Rano',
            'Rimin Gado',
            'Rogo',
            'Shanono',
            'Sumaila',
            'Takai',
            'Tarauni',
            'Tofa',
            'Tsanyawa',
            'Tudun Wada',
            'Ungogo',
            'Warawa',
            'Wudil',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KT',
          stateName: 'Katsina',
          lgas: [
            'Bakori',
            'Batagarawa',
            'Batsari',
            'Baure',
            'Bindawa',
            'Charanchi',
            'Dandume',
            'Danja',
            'Dan Musa',
            'Daura',
            'Dutsi',
            'Dutsin Ma',
            'Faskari',
            'Funtua',
            'Ingawa',
            'Jibia',
            'Kafur',
            'Kaita',
            'Kankara',
            'Kankia',
            'Katsina',
            'Kurfi',
            'Kusada',
            "Mai'Adua",
            'Malumfashi',
            'Mani',
            'Mashi',
            'Matazu',
            'Musawa',
            'Rimi',
            'Sabuwa',
            'Safana',
            'Sandamu',
            'Zango',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KE',
          stateName: 'Kebbi',
          lgas: [
            'Aleiro',
            'Arewa Dandi',
            'Argungu',
            'Augie',
            'Bagudo',
            'Birnin Kebbi',
            'Bunza',
            'Dandi',
            'Fakai',
            'Gwandu',
            'Jega',
            'Kalgo',
            'Koko/Besse',
            'Maiyama',
            'Ngaski',
            'Sakaba',
            'Shanga',
            'Suru',
            'Wasagu/Danko',
            'Yauri',
            'Zuru',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KO',
          stateName: 'Kogi',
          lgas: [
            'Adavi',
            'Ajaokuta',
            'Ankpa',
            'Bassa',
            'Dekina',
            'Ibaji',
            'Idah',
            'Igalamela Odolu',
            'Ijumu',
            'Kabba/Bunu',
            'Kogi',
            'Lokoja',
            'Mopa Muro',
            'Ofu',
            'Ogori/Magongo',
            'Okehi',
            'Okene',
            'Olamaboro',
            'Omala',
            'Yagba East',
            'Yagba West',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'KW',
          stateName: 'Kwara',
          lgas: [
            'Asa',
            'Baruten',
            'Edu',
            'Ekiti',
            'Ifelodun',
            'Ilorin East',
            'Ilorin South',
            'Ilorin West',
            'Irepodun',
            'Isin',
            'Kaiama',
            'Moro',
            'Offa',
            'Oke Ero',
            'Oyun',
            'Pategi',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'LA',
          stateName: 'Lagos',
          lgas: [
            'Agege',
            'Ajeromi-Ifelodun',
            'Alimosho',
            'Amuwo-Odofin',
            'Apapa',
            'Badagry',
            'Epe',
            'Eti Osa',
            'Ibeju-Lekki',
            'Ifako-Ijaiye',
            'Ikeja',
            'Ikorodu',
            'Kosofe',
            'Lagos Island',
            'Lagos Mainland',
            'Mushin',
            'Ojo',
            'Ibeju',
            'Gbagada',
            'Ajah',
            'Ipaja',
            'Abule Egba',
            'Magodo',
            'Ikotun',
            'Igando',
            'Oshodi-Isolo',
            'Shomolu',
            'Surulere',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'NA',
          stateName: 'Nasarawa',
          lgas: [
            'Akwanga',
            'Awe',
            'Doma',
            'Karu',
            'Keana',
            'Keffi',
            'Kokona',
            'Lafia',
            'Nasarawa',
            'Karu',
            'Nasarawa Egon',
            'Obi',
            'Toto',
            'Wamba',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'NI',
          stateName: 'Niger',
          lgas: [
            'Agaie',
            'Agwara',
            'Bida',
            'Borgu',
            'Bosso',
            'Chanchaga',
            'Edati',
            'Gbako',
            'Gurara',
            'Katcha',
            'Kontagora',
            'Lapai',
            'Lavun',
            'Magama',
            'Mariga',
            'Mashegu',
            'Mokwa',
            'Moya',
            'Paikoro',
            'Rafi',
            'Rijau',
            'Shiroro',
            'Suleja',
            'Tafa',
            'Wushishi',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'OG',
          stateName: 'Ogun',
          lgas: [
            'Abeokuta North',
            'Abeokuta South',
            'Ado-Odo/Ota',
            'Egbado North',
            'Egbado South',
            'Ewekoro',
            'Ifo',
            'Sango-ota',
            'Ijebu East',
            'Ijebu North',
            'Ijebu North East',
            'Ijebu Ode',
            'Ikenne',
            'Imeko Afon',
            'Ipokia',
            'Obafemi Owode',
            'Odeda',
            'Odogbolu',
            'Ogun Waterside',
            'Remo North',
            'Shagamu',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'ON',
          stateName: 'Ondo',
          lgas: [
            'Akoko North-East',
            'Akoko North-West',
            'Akoko South-East',
            'Akoko South-West',
            'Akure North',
            'Akure South',
            'Ese Odo',
            'Idanre',
            'Ikare akoko',
            'Ifedore',
            'Ilaje',
            'Ile Oluji/Okeigbo',
            'Irele',
            'Odigbo',
            'Okitipupa',
            'Ondo East',
            'Ondo West',
            'Ose',
            'Owo',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'OS',
          stateName: 'Osun',
          lgas: [
            'Aiyedaade',
            'Aiyedire',
            'Atakunmosa East',
            'Atakunmosa West',
            'Boluwaduro',
            'Boripe',
            'Ede North',
            'Ede South',
            'Egbedore',
            'Ejigbo',
            'Ife Central',
            'Ede',
            'Ilesa',
            'Olorunda osun',
            'Ife East',
            'Ife North',
            'Ife South',
            'Ifedayo',
            'Ifelodun',
            'Ila',
            'Ilesa East',
            'Ilesa West',
            'Irepodun',
            'Irewole',
            'Isokan',
            'Iwo',
            'Obokun',
            'Odo Otin',
            'Ola Oluwa',
            'Olorunda',
            'Oriade',
            'Orolu',
            'Osogbo',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'OY',
          stateName: 'Oyo',
          lgas: [
            'Afijio',
            'Akinyele',
            'Atiba',
            'Atisbo',
            'Egbeda',
            'Ibadan North',
            'Ibadan North-East',
            'Ibadan North-West',
            'Ibadan South-East',
            'Ibadan South-West',
            'Ibarapa Central',
            'Ibarapa East',
            'Ibarapa North',
            'Ido',
            'Irepo',
            'Iseyin',
            'Itesiwaju',
            'Iwajowa',
            'Kajola',
            'Lagelu',
            'Ogbomosho North',
            'Ogbomosho South',
            'Ogo Oluwa',
            'Olorunsogo',
            'Oluyole',
            'Ona Ara',
            'Orelope',
            'Ori Ire',
            'Oyo East',
            'Oyo West',
            'Saki East',
            'Saki West',
            'Surulere',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'PL',
          stateName: 'Plateau',
          lgas: [
            'Barkin Ladi',
            'Bassa',
            'Bokkos',
            'Jos East',
            'Jos North',
            'Jos South',
            'Kanam',
            'Kanke',
            'Langtang North',
            'Langtang South',
            'Mangu',
            'Mikang',
            'Pankshin',
            "Qua'an Pan",
            'Riyom',
            'Shendam',
            'Wase',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'RI',
          stateName: 'Rivers',
          lgas: [
            'Abua/Odual',
            'Ahoada East',
            'Ahoada West',
            'Akuku-Toru',
            'Andoni',
            'Asari-Toru',
            'Bonny',
            'Degema',
            'Eleme',
            'Emuoha',
            'Etche',
            'Gokana',
            'Ikwerre',
            'Ulakwo',
            'Obio-akpor',
            'Khana',
            'Obio/Akpor',
            'Ogba/Egbema/Ndoni',
            'Ogu/Bolo',
            'Okrika',
            'Omuma',
            'Opobo/Nkoro',
            'Oyigbo',
            'Port Harcourt',
            'Tai',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'SO',
          stateName: 'Sokoto',
          lgas: [
            'Binji',
            'Bodinga',
            'Dange Shuni',
            'Gada',
            'Goronyo',
            'Gudu',
            'Gwadabawa',
            'Illela',
            'Isa',
            'Kebbe',
            'Kware',
            'Rabah',
            'Sabon Birni',
            'Shagari',
            'Silame',
            'Sokoto North',
            'Sokoto South',
            'Tambuwal',
            'Tangaza',
            'Tureta',
            'Wamako',
            'Wurno',
            'Yabo',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'TA',
          stateName: 'Taraba',
          lgas: [
            'Ardo Kola',
            'Bali',
            'Donga',
            'Gashaka',
            'Gassol',
            'Ibi',
            'Jalingo',
            'Karim Lamido',
            'Kurmi',
            'Lau',
            'Sardauna',
            'Takum',
            'Ussa',
            'Wukari',
            'Yorro',
            'Zing',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'YO',
          stateName: 'Yobe',
          lgas: [
            'Bade',
            'Bursari',
            'Damaturu',
            'Fika',
            'Fune',
            'Geidam',
            'Gujba',
            'Gulani',
            'Jakusko',
            'Karasuwa',
            'Machina',
            'Nangere',
            'Nguru',
            'Potiskum',
            'Tarmuwa',
            'Yunusari',
            'Yusufari',
          ].sort((a, b) => a.localeCompare(b)),
        },
        {
          stateId: 'ZA',
          stateName: 'Zamfara',
          lgas: [
            'Anka',
            'Bakura',
            'Birnin Magaji/Kiyaw',
            'Bukkuyum',
            'Bungudu',
            'Gummi',
            'Gusau',
            'Kaura Namoda',
            'Maradun',
            'Maru',
            'Shinkafi',
            'Talata Mafara',
            'Tsafe',
            'Zurmi',
          ].sort((a, b) => a.localeCompare(b)),
        },
      ];

      return nigerianStates;
    } catch (error) {
      throw error;
    }
  }
}
